spring:
  messages:
    basename: messages,errors
  datasource:
    url: jdbc:h2:tcp://localhost/~/itemservice
    username: sa
    password:
    driver-class-name: org.h2.Driver
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG

openai:
  api:
    key:
